services:
  # Backend API
  - type: web
    name: instamator-backend
    env: node
    plan: free
    region: oregon
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production

  # Frontend (static site)
  - type: web
    name: instamator-frontend
    env: static
    plan: free
    region: oregon
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    envVars:
      - key: VITE_API_URL
        generateValue: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html